Nest/member_newModule
mip-work/backend pull request #53
Opened 2024-03-13 02:29 UTC by DaviBispo16

refactor: refactoring repository of the member module
refactor: refactoring services of the member module 
fix: add decorators to the controller in the member module 
fix: remove current member from services in member module

2024-03-13 17:47 UTC, victorzix requested changes

2024-03-13 17:47 UTC, victorzix commented on nest-backend/src/modules/member/controllers/member.controllers.ts
> +  @UseGuards(MemberGuard)
Aqui apenas membros com permissão deveriam poder atualizar uma posição

2024-03-13 17:47 UTC, victorzix commented on nest-backend/src/modules/member/services/member.services.ts
>      );
remover lógica de currentuser

2024-03-14 00:27 UTC, DaviBispo16 commented
alterações feitas!

2024-03-14 16:03 UTC, victorzix approved these changes

2024-03-14 16:04 UTC, merged